version: "3.8"

services:
  miapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5087:8080"
      - "7165:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
