version: "3.9"

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "5087:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq

  notification:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification
    entrypoint: ["dotnet", "/app/WebApi_csarp.dll", "notification"]
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
